# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Build and E2E Test

on:
  push:
    branches:
      - main
      - 'renovate/*'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    if: |
      !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/'))
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            # https://github.com/microsoft/playwright/issues/11932
            E2E: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test:e2e:ci
          - os: macos-latest
            E2E: yarn test:e2e:ci
          - os: windows-latest
            E2E: yarn test:e2e:ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 20

      - run: yarn install --immutable

      - run: yarn ship:auto

      - name: Create SPDX document
        run: yarn spdx

      - name: Verify name in SPDX document on MacOS and Ubuntu
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: |
          set -e
          name=$(jq .name opossum-ui.spdx.json -r)
          echo "name=$name"
          if [[ "$name" != "opossum-ui" ]]; then
            echo "Name in SPDX document is not opossum-ui"
            exit 1
          fi

      - name: Verify name in SPDX document on Windows
        if: matrix.os == 'windows-latest'
        run: |
          $name=jq .name opossum-ui.spdx.json -r
          echo "name=$name"
          if ("$name" -ne "opossum-ui") {
            echo "Name in SPDX document is not opossum-ui"
            exit 1
          }

      - run: ${{ matrix.E2E }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: artifacts
          path: src/e2e-tests/artifacts
          retention-days: 30
